# -*- coding: utf-8 -*-
"""Projeto de Parceria - Semantix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GRi6n3kVptVZHA8ON_slsp68giGgdOc-
"""

pip install pandas matplotlib seaborn

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Carregar o arquivo CSV
data = pd.read_csv('Food Waste data and research - by country.csv')

# Exibir as Primeiras linhas do dataset
print(data.head())

# Verificar informações gerais do dataset
data.info()

# Resumo estatístico
data.describe()

# Verificar valores nulos
data.isnull().sum()

# Remover Colunas irrelevantes (se necessário) - Ajuste Conforme os dados
data_cleaned = data.dropna()

# Distribuição do desperdício alimentar por páis
plt.figure(figsize=(12,6))
sns.barplot(x='Country', y='combined figures (kg/capita/year)', data=data_cleaned)
plt.xticks(rotation=90)
plt.title('Desperdício Alimentar por País')
plt.xlabel('País')
plt.ylabel('Desperdício (kg per capita por ano)')
plt.show()

# Correlação entre desperdício alimentar e outros fatores
plt.figure(figsize=(10,6))
numeric_data = data_cleaned.select_dtypes(include=['number']) # Seleciona apenas as colunas numéricas para calcular a correlação
sns.heatmap(numeric_data.corr(), annot=True, cmap='coolwarm')
plt.title('Mapa de Correlação')
plt.show()

# Salvar dataset limpo
output_path = 'food_waste_data_cleaned.csv'
data_cleaned.to_csv(output_path, index=False)
print(f'Dataset limpo salvo em: {output_path}')